spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: prod
    import: classpath:sub/application-db.yml, classpath:sub/application-token.yml
---
spring:
  config:
    activate:
      on-profile: dev
    import: classpath:dev/application-dev.yml, classpath:sub/application-token.yml
