
= API Docs
Pomin-Owner API Docs
:icons: font
:source-highlighter: highlightjs
:toc: left
:toc-title: API
:toclevels: 2
:sectlinks:

== Store
=== Store : save
operation::store/save[snippets='http-request,http-response']

=== Category : save
operation::store/category/save[snippets='http-request,http-response']

=== Image : save
operation::store/image/save[snippets='http-request,http-response,request-parts']

=== Info : update
operation::store/info/update[snippets='http-request,http-response']

=== Info : delete
operation::store/info/delete[snippets='http-request,http-response']

=== Phone Number : update
operation::store/phone-number/update[snippets='http-request,http-response']

=== Phone Number : delete
operation::store/phone-number/delete[snippets='http-request,http-response']

== Menu
=== Menu : save
operation::menu/save[snippets='http-request,http-response,request-parts,request-part-request-fields']

=== Menu : update
operation::menu/update[snippets='http-request,http-response,request-parts,request-part-request-fields']

=== Menu : add Option Group
operation::menu/add-option-group[snippets='http-request,http-response,path-parameters']

== Option Group
=== Option Group : save
operation::option-group/save[snippets='http-request,http-response']

=== Option Group : update
operation::option-group/update[snippets='http-request,http-response']

=== Option Group : find
operation::option-group/find[snippets='http-request,http-response,response-fields']

=== Option Group : delete
operation::option-group/delete[snippets='http-request,http-response']

== Option
=== Option : save
operation::option/save[snippets='http-request,http-response']

=== Option : update
operation::option/update[snippets='http-request,http-response']

=== Option : find
operation::option/find[snippets='http-request,http-response,response-fields']

=== Option : delete
operation::option/delete[snippets='http-request,http-response']

== Order
=== Order : approve
operation::order/approve[snippets='http-request,http-response']

=== Order : reject
operation::order/reject[snippets='http-request,http-response']

=== Order : receive
operation::order/receive[snippets='http-request,http-response']

=== Order : ready
operation::order/ready[snippets='http-request,http-response']

=== Order : today-orders
operation::order/today-orders[snippets='http-request,http-response']

== Settlement
=== Settlement : by-order
operation::settlement/by-order[snippets='http-request,http-response']

=== Settlement : by-store
operation::settlement/by-store[snippets='http-request,http-response']
